html seat booking task
kottans/frontend-2021-classroom pull request #21
Opened 2021-01-27 23:32 UTC by alstep07

### html-movie-seat-booking

[Demo](https://alstep07.github.io/movie-seat-booking/)

The code is submitted in a dedicated feature branch.
Please, review.

2021-01-28 08:47 UTC, ses3332002 commented
Great work!
But why you set tabindex="0" on H1 and IMG tags?

2021-01-28 09:04 UTC, alstep07 commented
> Great work!
> But why you set tabindex="0" on H1 and IMG tags?

For screen-readers.

2021-01-30 21:07 UTC, A-Ostrovnyy requested changes
Good work!
Se my comments below.

2021-01-30 21:07 UTC, A-Ostrovnyy commented on submissions/alstep07/html-movie-seat-booking/index.html
> +            <h1 class="header__title" tabindex="0">Choose your seats</h1>
By default screen readers have navigation by headings, no need to add `tabindex="0"` to headings.

2021-01-30 21:07 UTC, A-Ostrovnyy commented on submissions/alstep07/html-movie-seat-booking/index.html
> +                    <div class="example__desc">N/A</div>
For text content better to use text tags such as `<p>` etc.

2021-01-30 21:07 UTC, A-Ostrovnyy commented on submissions/alstep07/html-movie-seat-booking/index.html
> +                <img src="./img/screen.svg" tabindex="0" class="screen__img" alt="screen">
By default screen readers read all added images in html. No need to add `tabindex` attribute to the images.

2021-01-30 21:07 UTC, A-Ostrovnyy commented on submissions/alstep07/html-movie-seat-booking/index.html
> +                <h2 tabindex="0" class="visually-hidden">cinema hall</h2>
Same as at line 16.

2021-01-30 21:29 UTC, alstep07 commented on submissions/alstep07/html-movie-seat-booking/index.html
> +            <h1 class="header__title" tabindex="0">Choose your seats</h1>
Thank you for your review! I used google chrome extension "Screen Reader" and it did not read headers, thats why I added tabindex. I will remove it and test in screen reader, wich you recomended in todays lection.

2021-01-31 08:44 UTC, A-Ostrovnyy approved these changes
Well done!

2021-01-31 08:44 UTC, merged