HTML movie seat booking.
kottans/frontend-2021-classroom pull request #39
Opened 2021-02-03 00:05 UTC by yaripey

[Demo](https://yaripey.github.io/cinema-html-css/)

2021-02-04 22:18 UTC, A-Ostrovnyy requested changes
Good work!
Extra like for the Ukrainian language.
See my comments below.

2021-02-04 22:18 UTC, A-Ostrovnyy commented on submissions/yaripey/html-movie-seat-booking/index.html
> +        <li><a class="path-link active" href="#">Придбати білет</a></li>
In Ukrainian "квиток". You use that word later)

2021-02-04 22:18 UTC, A-Ostrovnyy commented on submissions/yaripey/html-movie-seat-booking/index.html
> +            <li><a class="settings-buttons-link sign-out" href="#"></a></li>
Logically it's no navigation, no need to use navigation markup.

2021-02-04 22:18 UTC, A-Ostrovnyy commented on submissions/yaripey/html-movie-seat-booking/index.html
> +                  />
Add attribute `value` to the input.

2021-02-04 22:18 UTC, A-Ostrovnyy commented on submissions/yaripey/html-movie-seat-booking/index.html
> +                  <div class="input-label">19 лют</div>
For date use `time` tag with `datetime` attribute.

2021-02-05 10:37 UTC, ses3332002 commented
Why you used lang="en" in <html>? 
I guess for Ukrainian it must be "uk".

2021-02-05 10:59 UTC, yaripey commented
> Why you used lang="en" in html tag?
> I guess for Ukrainian it must be "uk".

Thanks for pointing that out!

2021-02-05 20:30 UTC, A-Ostrovnyy approved these changes
Well done!

2021-02-05 20:30 UTC, merged