html-movie-seat-booking
kottans/frontend-2021-classroom pull request #55
Opened 2021-02-05 20:33 UTC by zalevskyi

### html-movie-seat-booking

[Demo](https://zalevskyi.github.io/kottans-frontend/practice/html-movie-seat-booking/)

Please, review.

2021-02-09 20:41 UTC, A-Ostrovnyy requested changes
Good work!
See my comment below!

2021-02-09 20:41 UTC, A-Ostrovnyy commented on submissions/zalevskyi/html-movie-seat-booking/app.css
> +.seat {
Add styles on `:hover`, `:active`, and `:focus` states. Also, add `cursor: pointer;`

2021-02-09 20:41 UTC, A-Ostrovnyy commented on submissions/zalevskyi/html-movie-seat-booking/app.css
> +.book__button {
Same as at line 32

2021-02-11 22:16 UTC, zalevskyi commented
Thank you for the review!
All recommendations are implemented (Add styles on :hover, :active, and :focus states. Also, add cursor: pointer;)
Please review once more.

2021-02-12 06:44 UTC, A-Ostrovnyy approved these changes
Well done!

2021-02-12 06:44 UTC, merged