nadsatt/movie-seat-booking
kottans/frontend-2021-classroom pull request #56
Opened 2021-02-05 21:57 UTC by nadsatt

Sorry for such ugly files and buggy app, i will improve it tomorrow!

2021-02-09 21:08 UTC, A-Ostrovnyy requested changes
Eye candy work!
See my comments below.

2021-02-09 21:08 UTC, A-Ostrovnyy commented on submissions/nadsatt/index.html
> +      <h3 class="movie-info__name">Baby driver</h3>
Use `h1` for main page title.

2021-02-09 21:08 UTC, A-Ostrovnyy commented on submissions/nadsatt/index.html
> +              <input class="control__check-input control__input" type="checkbox" name="1" disabled>
Add and fill attribute `value` to the input.

2021-02-09 21:08 UTC, A-Ostrovnyy commented on submissions/nadsatt/index.html
> +              <input class="control__check-input control__input" type="checkbox" name="17">
Add styles on `:hover`, and `:active` states.

2021-02-13 12:48 UTC, nadsatt commented
@A-Ostrovnyy thank you for review!

What was done:
- improved html & css code (core idea and html skeleton remained the same)
- added fixes according to your comments

2021-02-13 13:21 UTC, A-Ostrovnyy approved these changes
Well done!

2021-02-13 13:21 UTC, merged