Iakow/movie-seat-booking
kottans/frontend-2021-classroom pull request #58
Opened 2021-02-06 01:59 UTC by Iakow

[Demo](https://iakow.github.io/kottans-movie/)
[Code](https://github.com/kottans/frontend-2021-classroom/tree/iakow/movie-seat-booking/submissions/iakow)

2021-02-09 21:30 UTC, A-Ostrovnyy requested changes
Good work!
See my comment below!

2021-02-09 21:30 UTC, A-Ostrovnyy commented on submissions/iakow/index.html
> +        <h3 class="movie-name">"Simplicity"</h3>
For main page title use `h1` tag.

2021-02-09 21:30 UTC, A-Ostrovnyy commented on submissions/iakow/index.html
> +        </time>
🔥

2021-02-10 15:47 UTC, A-Ostrovnyy requested changes
Don't forget to update your demo, also, remove files not for review(images, etc)

2021-02-10 17:06 UTC, Iakow commented
> Don't forget to update your demo, also, remove files not for review(images, etc)

Sorry, it seemed to me that Ivan expressed uncertainty about this at the first zoom session. In any case - done)

2021-02-10 19:29 UTC, A-Ostrovnyy approved these changes
Well done!

2021-02-10 19:29 UTC, merged