Lu sure/movie seat booking
kottans/frontend-2021-classroom pull request #60
Opened 2021-02-06 10:10 UTC by Lu-sure

**Movie seat booking task**

[Demo](https://lu-sure.github.io/Movie_seat_booking/)

The code is submitted in a dedicated feature branch.
Please, review.

2021-02-10 14:37 UTC, A-Ostrovnyy requested changes
Nice work, iconic movie)
See my comment below!

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/index.html
> +                <span class="slash">|</span>
You can use pseudoelement for it)

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/index.html
> +                alt="the pale woman's face with brown eyes and brown-yellow butterfly on lips"
🔥

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/index.html
> +            <h2 class="film-name">"The Silence of the Lambs"</h2>
Use `h1` tag for main heading of the page.

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/index.html
> +        </div>
🔥

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/index.html
> +                <input class="confirm-but" type="submit" value="Book now">
Add style s on `:hover`, `:active`, and `focus` states.

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/style.css
> +    background-color: rgb(78, 104, 160);;
Remove extra semicolon.)

2021-02-10 14:37 UTC, A-Ostrovnyy commented on submissions/Lu-sure/movie-seat-booking/style.css
> +
Remove unused lines.

2021-02-22 13:24 UTC, Lu-sure commented
Changes are made)
I've installed prettier only now, so all the html shifted, my bad.
Thanks for your 🔥🔥

2021-02-25 22:05 UTC, A-Ostrovnyy approved these changes
Well done!

2021-02-25 22:06 UTC, merged