Task2. DOM-JS
kottans/frontend-2021-classroom pull request #64
Opened 2021-02-13 18:30 UTC by UA-girl

[Demo](https://ua-girl.github.io/Booking-KottansHW/)
[CodeBase](https://github.com/UA-girl/Booking-KottansHW)

Please, review. The data in the table below the form updates each time user selects/updates date, time, city or selects/unselects seats.

2021-02-27 21:07 UTC, A-Ostrovnyy requested changes
Good work!

2021-02-27 21:07 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +(function () {
No need to wrap all your code by IIFE.

2021-02-27 21:07 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +    dateString: function () {
Good practice function name must contain/start verb.
The current name is too generic.

2021-02-27 21:07 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +        );
Not a good practice. You already have NodeList with 'forEach' method, no need for extra transformation.

2021-02-27 21:07 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +  function updateTable(name, value) {
Same as at line 13

2021-02-27 21:07 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +  let order = {
Why you don't use class for this?

2021-02-27 21:07 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +    switch (name) {
Switch for two cases is overkill. It's fine but simple `if else` will be enough.

2021-02-27 22:23 UTC, UA-girl commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +(function () {
I wanted to "simulate" a moduleness ))) and hide variables from global scope.

2021-02-28 14:12 UTC, UA-girl commented
Thank you for advices ) Changed a little bit a logic - maybe, this way it would be better?

2021-02-28 14:42 UTC, A-Ostrovnyy requested changes
Good work!

2021-02-28 14:42 UTC, A-Ostrovnyy commented on submissions/UA-girl/Task-JS-DOM/js/main.js
> +window.onload = function () {
Avoid adding event listeners using `onevent` attribute use `addEventListener` for this.

2021-02-28 14:58 UTC, A-Ostrovnyy approved these changes
Well done!

2021-02-28 15:00 UTC, A-Ostrovnyy commented
@UA-girl please resolve conflicts and let me know, after that, I will merge your work)

2021-02-28 15:04 UTC, UA-girl commented
Oh, but this is not my folder (( and have not any folders on my machine via this branch except my own. Can you suggest me, how can I resolve? maybe, make pull from this branch? To get this folder on my machine? This is first time I get such problem ((

2021-02-28 15:21 UTC, A-Ostrovnyy commented
Switch to branch `main` then pull all changes to your local branch `main` and then merge `main` branch into your task branch (`UA-girl/js-dom-task`)

2021-02-28 15:57 UTC, UA-girl commented
Alexandr, I've made it! ))) Thank you for advise - it helped )

2021-02-28 16:06 UTC, merged