js-movie-seat-booking task
kottans/frontend-2021-classroom pull request #69
Opened 2021-02-16 15:05 UTC by madmaxWMFU

[Demo](https://madmaxwmfu.github.io/tikets-app/)

2021-02-28 15:01 UTC, A-Ostrovnyy requested changes
Good work!
See my comments below.

2021-02-28 15:01 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/data.json
> +}
Add an empty line at the end of each file.

2021-02-28 15:01 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    return fetch('./data/data.json')
You should handle fetch response status. [Read more](https://www.tjvantoll.com/2015/09/13/fetch-and-errors/)

2021-02-28 15:01 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    filmTime.setAttribute('datetime', time);
Better use template string for it.

2021-02-28 15:01 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    var ticketWrap = document.createElement("template");
Use `let` or `const` for defining variables.

2021-02-28 15:01 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    })
```suggestion
    cart.querySelectorAll('.form__ticket').forEach((item) => {
        if(item.getAttribute('id') === id) {
           item.remove(); 
        }
    })
```

Use `querySelectorAll` instead `Array.form` he has included forEach method.

2021-02-28 15:01 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +window.onload = init();
Avoid adding event listeners using `onevent` attribute use addEventListener for this.

2021-03-01 14:43 UTC, madmaxWMFU commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    filmTime.setAttribute('datetime', time);
Here the data is written to already existing elements. Or is it better to redraw them?

2021-03-01 21:52 UTC, A-Ostrovnyy requested changes
Good work
Check all issues before pushing)

2021-03-01 21:52 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    var ticketWrap = document.createElement("template");
Still not fixed)

2021-03-01 21:52 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +window.onload = init();
Not fixed yet.

2021-03-01 21:52 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    })
Not fixed yet

2021-03-01 21:52 UTC, A-Ostrovnyy commented on submissions/madmaxWMFU/js-movie-booking/app.js
> +    filmTime.setAttribute('datetime', time);
Better redraw instead of finding each element and adding classnames/attributes of other things.

2021-03-03 05:55 UTC, madmaxWMFU commented
Changed locally, but forgot to push 🤦‍♂️🤦‍♂️

2021-03-03 07:25 UTC, A-Ostrovnyy approved these changes
Well done!

2021-03-03 07:25 UTC, merged

2021-03-03 09:11 UTC, madmaxWMFU commented
Thank's a lot!