Webdevtoday/html movie seat booking
kottans/frontend-2021-classroom pull request #71
Opened 2021-02-17 09:42 UTC by webdevtoday

Changed a view of focused state of checkboxes.

2021-02-28 15:09 UTC, A-Ostrovnyy commented
@webdevtoday Please provide us with a link to the working demo.

2021-02-28 15:11 UTC, A-Ostrovnyy requested changes

2021-02-28 15:11 UTC, A-Ostrovnyy commented on submissions/webdevtoday/html-movie-seat-booking/index.html
> +    <title>Task</title>
Add appropriate title

2021-02-28 15:11 UTC, A-Ostrovnyy commented on submissions/webdevtoday/html-movie-seat-booking/index.html
> +
Remove unused lines.

2021-03-07 17:09 UTC, webdevtoday commented on submissions/webdevtoday/html-movie-seat-booking/index.html
> +    <title>Task</title>
I'll fix it

2021-03-07 17:09 UTC, webdevtoday commented on submissions/webdevtoday/html-movie-seat-booking/index.html
> +
I'll fix it

2021-03-07 18:33 UTC, webdevtoday commented on submissions/webdevtoday/html-movie-seat-booking/index.html
> +    <title>Task</title>
I've done it

2021-03-07 18:33 UTC, webdevtoday commented on submissions/webdevtoday/html-movie-seat-booking/index.html
> +
I've done it

2021-03-18 22:10 UTC, A-Ostrovnyy commented
@webdevtoday can you add a link on the demo page?)

2021-03-19 04:11 UTC, webdevtoday commented
> @webdevtoday can you add a link on the demo page?)

Oh, sorry, I'll add it

2021-03-20 16:41 UTC, webdevtoday commented
> @webdevtoday can you add a link on the demo page?)

I've done it

2021-03-20 22:06 UTC, A-Ostrovnyy approved these changes
Good Work!

2021-03-20 22:06 UTC, merged